services:
    barbara.quiz_details_manager:
        class: AppBundle\Model\QuizDetailsUserManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\QuizDetailsUser
            - @artesanus.user_manager
        calls:
            - [setSecurity, ['@security.context']]

    barbara.users_notifications_manager:
        class: AppBundle\Model\UserNotificationsManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\UserNotifications

    barbara.courses_notifications_manager:
        class: AppBundle\Model\CoursesNotificationsManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\CoursesNotifications
