services:
    barbara.username_certificate_type:
        class: AppBundle\Form\UsernameCertificateType
        tags:
            - { name: form.type, alias: barbara_username_certificate_type }

    barbara.quiz_details_user_type:
        class: AppBundle\Form\QuizDetailsUserType
        tags:
            - { name: form.type, alias: barbara_quiz_details_user_type }

    barbara.users_notifications_type:
        class: AppBundle\Form\UserNotificationsType
        tags:
            - { name: form.type, alias: barbara_users_notifications }

    barbara.courses_notifications_type:
        class: AppBundle\Form\CoursesNotificationsType
        tags:
            - { name: form.type, alias: barbara_courses_notifications_type }

    barbara.home_type:
        class: AppBundle\Form\HomeType
        tags:
            - { name: form.type, alias: barbara_home_type }

    barbara.videos_type:
        class: AppBundle\Form\VideosType
        tags:
            - { name: form.type, alias: barbara_videos_type }

    barbara.home_videos_type:
        class: AppBundle\Form\HomeVideosType
        tags:
            - { name: form.type, alias: barbara_home_videos_type }
