<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizDetailsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizDetailsUserRepository extends EntityRepository
{

    public function findQuizUser($quiz, $user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT q FROM AppBundle:QuizDetailsUser q
                 WHERE q.users  = :user
                 AND q.quizs     = :quiz
                '
            )
            ->setParameter('user', $user)
            ->setParameter('quiz', $quiz)
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }


    public function findQuestionsCourseUser($course, $user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT c FROM AppBundle:QuizDetailsUser c
                 LEFT JOIN c.questions q
                 LEFT JOIN q.itemsQuiz iq
                 LEFT JOIN iq.items i
                 LEFT JOIN i.modules m
                 LEFT JOIN m.courses co
                 WHERE c.users = :user
                 AND q.itemsQuiz = iq.id
                 AND iq.items = i.id
                 AND i.modules = m.id
                 AND m.courses = co.id
                 AND co.id = :course
                 ORDER BY c.id ASC
                '
            )
            ->setParameter('user', $user)
            ->setParameter('course', $course)
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }


}
