<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizDetailsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizDetailsUserRepository extends EntityRepository
{

    public function findQuizUser($quiz, $user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT q FROM AppBundle:QuizDetailsUser q
                 WHERE q.users  = :user
                 AND q.quizs     = :quiz
                '
            )
            ->setParameter('user', $user)
            ->setParameter('quiz', $quiz)
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

}
