<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserNotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationsRepository extends EntityRepository
{

    public function findNotificationsCourseUser($course, $user)
    {
        try {
            return $this->getEntityManager()->createQuery(
                'SELECT c FROM AppBundle:UserNotifications c
                 WHERE c.users = :user
                 AND c.courses = :course
                '
            )
            ->setParameter('user',$user->getId())
            ->setParameter('course',$course->getId())
            ->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }

}
